// Campus map data (generated by scripts/build_map.py) plus collision queries.

export type Pt = [number, number] // [x, z] in meters; +x east, +z south

export interface Building {
  pts: Pt[]
  h: number
  roof: string
  name?: string
  event?: boolean
}

export interface Campus {
  bounds: [number, number, number, number]
  spawn: Pt
  event: {
    name: string
    center: Pt
    pts: Pt[]
    h: number
    /** Klaus doors from OSM: [x, z, facing radians], placed just outside the wall. */
    entrances: [number, number, number][]
    /** Index into `entrances` of the HackGT main entrance. */
    main?: number
  } | null
  buildings: Building[]
  roads: { pts: Pt[]; w: number; foot: boolean }[]
  areas: { pts: Pt[]; kind: string }[]
  trees: Pt[]
}

export async function loadCampus(): Promise<Campus> {
  const res = await fetch('/campus.json')
  if (!res.ok) throw new Error(`campus.json: ${res.status}`)
  return res.json()
}

export function pointInPoly(x: number, z: number, poly: Pt[]): boolean {
  let inside = false
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, zi] = poly[i]
    const [xj, zj] = poly[j]
    if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) inside = !inside
  }
  return inside
}

function distToSegment(x: number, z: number, a: Pt, b: Pt): number {
  const dx = b[0] - a[0]
  const dz = b[1] - a[1]
  const len2 = dx * dx + dz * dz
  const t = len2 ? Math.max(0, Math.min(1, ((x - a[0]) * dx + (z - a[1]) * dz) / len2)) : 0
  return Math.hypot(x - (a[0] + t * dx), z - (a[1] + t * dz))
}

const CELL = 40

/** Spatial hash over building footprints for fast "am I inside a wall" checks. */
export class Collider {
  private grid = new Map<string, number[]>()
  private campus: Campus

  constructor(campus: Campus) {
    this.campus = campus
    campus.buildings.forEach((b, i) => {
      const xs = b.pts.map((p) => p[0])
      const zs = b.pts.map((p) => p[1])
      for (let gx = Math.floor(Math.min(...xs) / CELL); gx <= Math.floor(Math.max(...xs) / CELL); gx++)
        for (let gz = Math.floor(Math.min(...zs) / CELL); gz <= Math.floor(Math.max(...zs) / CELL); gz++) {
          const k = `${gx},${gz}`
          const list = this.grid.get(k)
          if (list) list.push(i)
          else this.grid.set(k, [i])
        }
    })
  }

  private near(x: number, z: number): number[] {
    return this.grid.get(`${Math.floor(x / CELL)},${Math.floor(z / CELL)}`) ?? []
  }

  /** True if a circle of radius r at (x, z) overlaps a building or leaves the map. */
  blocked(x: number, z: number, r = 0.5): boolean {
    const [x0, z0, x1, z1] = this.campus.bounds
    if (x < x0 || x > x1 || z < z0 || z > z1) return true
    for (const i of this.near(x, z)) {
      const pts = this.campus.buildings[i].pts
      if (pointInPoly(x, z, pts)) return true
      for (let a = 0, b = pts.length - 1; a < pts.length; b = a++)
        if (distToSegment(x, z, pts[a], pts[b]) < r) return true
    }
    return false
  }

  /** Name of the building whose footprint is nearest (within `range` m). */
  nearestNamed(x: number, z: number, range = 18): Building | null {
    let best: Building | null = null
    let bestD = range
    for (const i of this.near(x, z)) {
      const b = this.campus.buildings[i]
      if (!b.name) continue
      for (let a = 0, c = b.pts.length - 1; a < b.pts.length; c = a++) {
        const d = distToSegment(x, z, b.pts[a], b.pts[c])
        if (d < bestD) {
          bestD = d
          best = b
        }
      }
    }
    return best
  }

  /** Nearest walkable point to (x, z), searching outward in a spiral. */
  freeSpot(x: number, z: number): Pt {
    for (let r = 0; r < 200; r += 2)
      for (let a = 0; a < Math.PI * 2; a += Math.PI / 8) {
        const px = x + Math.cos(a) * r
        const pz = z + Math.sin(a) * r
        if (!this.blocked(px, pz, 1)) return [px, pz]
        if (r === 0) break
      }
    return [x, z]
  }
}
